-- 1. Tabla de Productos de Proveedores
-- Almacena el catálogo de productos y el "precio actual" que se actualizará tras cada negociación.
CREATE TABLE IF NOT EXISTS public."Neg_productos" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id TEXT NOT NULL, -- Relacionado con el ID/NIT del proveedor
    descripcion TEXT NOT NULL,
    precio_actual NUMERIC NOT NULL DEFAULT 0,
    cantidad_mensual NUMERIC DEFAULT 1,
    tipo TEXT DEFAULT 'Ahorro', -- 'Ahorro' o 'Avoidance'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Historial de Negociaciones
-- Guarda un registro cada vez que se cambia un precio.
CREATE TABLE IF NOT EXISTS public."Neg_historial_precios" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public."Neg_productos"(id),
    fecha_cambio TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    precio_anterior NUMERIC NOT NULL,
    precio_nuevo NUMERIC NOT NULL,
    ahorro_generado NUMERIC,
    usuario_id UUID -- Opcional, si quieres registrar quién hizo el cambio
);

-- 3. Datos de Prueba (Seed Data)
-- Insertamos los mismos datos que estabamos usando de prueba en el frontend
-- Reemplaza '123456789' con el ID del proveedor real si lo conoces
INSERT INTO public."Neg_productos" (supplier_id, descripcion, precio_actual, cantidad_mensual, tipo)
VALUES 
    ('123456789', 'Servicio de Mantenimiento Aire Acondicionado', 1500000, 2, 'Ahorro'),
    ('123456789', 'Licencias de Software Antivirus', 50000, 50, 'Avoidance'),
    ('123456789', 'Dotación de Uniformes (Camisas)', 45000, 100, 'Ahorro'),
    ('123456789', 'Servicio de Vigilancia 24/7', 8500000, 1, 'Ahorro'),
    ('900350418', 'Suministro de Papelería', 25000, 200, 'Ahorro');

-- Permisos (Rols básicos para que la app pueda leer/escribir)
ALTER TABLE public."Neg_productos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Neg_historial_precios" ENABLE ROW LEVEL SECURITY;

-- Política simple: Permitir todo (Ajustar para producción real)
CREATE POLICY "Acceso total a productos" ON public."Neg_productos" FOR ALL USING (true);
CREATE POLICY "Acceso total a historial" ON public."Neg_historial_precios" FOR ALL USING (true);

